#!/bin/bash

## Global consts ##
readonly activeUser=$USER
readonly activeUserHome=$HOME
readonly vmAmiID='ami-0498011f1d38eb4d7'
readonly vmSize='t2.medium'
readonly vmSG='sg-02bab4ce68aad6be0'
readonly vmIamRole='VmManagerS3AccessInstanceProfile'
readonly vmKeyPair=$activeUser
readonly privateKeyLocation=$activeUserHome'/'$vmKeyPair'-aws-vm-key.pem'

## Global vars ##
jq='./bin/jq-mac'
mac=false
linux=false
instanceId='not-assigned'

cd $(dirname ${BASH_SOURCE[0]})

## Functions ##
function check_os() {
  if [[ $OSTYPE == *'darwin'*  ]]; then
    mac=true
  elif [[ $OSTYPE == *'linux'*  ]]; then
    linux=true
  else
    finish_with_error 'Operating system not supported'
  fi
}

function create_key_pair() {
  printf '\n=> Generating you a first time VM key pair..'

  local awsResp=$(aws ec2 create-key-pair --key-name $vmKeyPair --query 'KeyMaterial' --output text > $privateKeyLocation)
  chmod 400 $privateKeyLocation

  printf ' done and written to ['$privateKeyLocation'].\n'
}

function welcome() {
  printf '\n************************************\n'
  printf "** Butcher\'s Encrypted VM Manager **\n"
  printf '*************** v0.1 ***************\n\n'
  printf '=> Running as user ['$activeUser']\n'
}

function init() {
  printf '=> Performing system checks..\n'

  check_os

  if [[ $linux == true ]]; then
    jq='./bin/jq-linux'
    printf '\e[32m\n\xE2\x9C\x94 Using Linux jq binary\e[m'
  fi

  if [[ ! -f $privateKeyLocation ]]; then
    printf '\nRead failed for default key ['$privateKeyLocation']. Probably first time run.\n'
    create_key_pair
    if [[ ! -f $privateKeyLocation ]]; then
      finish_with_error 'Read failed again for default key ['$privateKeyLocation']. Please verify.'
    fi
  fi

  printf '\e[32m\n\xE2\x9C\x94 Using AWS private key located at ['$privateKeyLocation']\e[m\n'

  if type 'aws' &> /dev/null; then
    printf '\e[32m\xE2\x9C\x94 Verified AWS CLI is installed\e[m\n'
  else
    printf '\e[31m\xE2\x9D\x8C AWS CLI not found on system, please install.\e[m\n'
    finish_with_error 'Unmet dependencies'
  fi
}

function check_for_running_instances() {
  printf '\n=> Contacting AWS..\n'

  local awsResp=$(aws ec2 describe-instances --filters 'Name=key-name,Values='$vmKeyPair 'Name=instance-state-code,Values=16')
  local runningCount=$(echo $awsResp | $jq -r '.Reservations | length')
  if (( $runningCount > 0 )); then
    instanceId=$(echo $awsResp | $jq -r '.Reservations[0].Instances[0].InstanceId')
    printf '\e[33m\nRunning instance for user ['$activeUser'] found, terminate or get password? [t|p]\e[m\n'
    read action
    if [[ $action == 't' || $action == 'T' ]]; then
      terminate_instance
    else
      if [[ $action == 'p' || $action == 'P' ]]; then
        get_admin_password
        check_for_running_instances
      else
        finish_with_error "Unrecognised action ['$action'], can only be \'t\' or \'p\'"
      fi
    fi
  fi

  return 1;
}

function launch_instance() {
  printf '\nSpawning new instance for ['$activeUser']..'
  local awsResp=$(aws ec2 run-instances --image-id $vmAmiID --count 1 --instance-type $vmSize --key-name $vmKeyPair --security-group-ids $vmSG --iam-instance-profile Name=$vmIamRole --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value='$activeUser'}]')
  instanceId=$(echo $awsResp | $jq -r '.Instances[0].InstanceId')

  if [[ $instanceId == *'i-'* ]]; then
    printf ' instance created with ID ['$instanceId']\n\n'
  else
    finish_with_error 'Instance could not be created, try again in a minute'
  fi
}

function get_admin_password() {
  printf '\n=> Obtaining instance administrator password..'
  poll_get_admin_password
}

function poll_get_admin_password() {
  local awsResp=$(aws ec2 get-password-data --instance-id $instanceId --priv-launch-key $privateKeyLocation)
  local password=$(echo $awsResp | $jq -r '.PasswordData')

  if [[ $password != '' ]]; then
    printf ' obtained and decoded.\n\n'
    printf 'You can now log into your Windows VM using:\n   - Username: Administrator\n   - Password: '
    printf '%s' $password
    printf '\n\n'

    if [[ $mac == true ]]; then
      echo $password | tr -d '\n' | pbcopy
      printf '\e[32mPassword has been copied to your clipboard.\e[m\n'
    fi
  else
    printf '.'
    sleep 10
    poll_get_admin_password
  fi
}

function get_public_dns() {
  printf '=> Obtain instance DNS for connecting..'

  local awsResp=$(aws ec2 describe-instances --instance-ids $instanceId)
  local dns=$(echo $awsResp | $jq -r '.Reservations[0].Instances[0].PublicDnsName')

  if [[ $dns != '' ]]; then
    printf '\e[32m\n\nInstance now accessible with DNS ['$dns']\e[m\n'
    if [[ $mac == true ]]; then
      echo $dns | tr -d '\n' | pbcopy
      printf '\e[32mDNS has been copied to your clipboard.\e[m\n'
    fi
  else
    sleep 5
    pollGetDNS
  fi
}

function terminate_instance() {
  printf '\n=> Terminating instance ['$instanceId']..\n'

  local awsResp=$(aws ec2 terminate-instances --instance-ids $instanceId)
  local statusCode=$(echo $awsResp | $jq -r '.TerminatingInstances[0].CurrentState.Code')

  if (( $statusCode == 32 )); then
    printf '\e[32mInstance has been successfully terminated. Job done.\e[m\n'
    #TODO: try again if failed?
    finish
  fi
}

function finish_with_error() {
  printf '\n\e[31mManager Finished. Exiting abnormally.\n'
  printf "Error: $1.\e[m\n"
  exit 1
}

function finish() {
  printf '\n\e[32mManager Finished. Exiting normally..\e[m\n'
  exit 0
}

## Main ##
welcome
init
check_for_running_instances

if (( $? == 1 )); then
  printf '\e[34m\nDo you want to launch a new instance now? [y|n]\e[m\n'
  read action
  if [[ $action == 'y' || $action == 'Y' ]]; then
    launch_instance
    printf '=> Waiting for Windows administrator password to be available (may take a few minutes) ..'
    poll_get_admin_password
    get_public_dns
    check_for_running_instances
  else
    if [[ $action == 'n' || $action == 'N' ]]; then
      finish
    fi
  fi
fi

finish
